//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSESSMENT
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int Max_mark { get; set; }
        public string grade { get; set; }
        public int ProgramID { get; set; }
        public int ModuleID { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual MODULE MODULE { get; set; }
        public virtual PROGRAM PROGRAM { get; set; }
    }
}
