//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COHORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COHORT()
        {
            this.COURSE_ENROLLMENT = new HashSet<COURSE_ENROLLMENT>();
        }
    
        public int ID { get; set; }
        public string a_year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSE_ENROLLMENT> COURSE_ENROLLMENT { get; set; }
    }
}
