//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_ENROLLMENT
    {
        public int Id { get; set; }
        public int StudentID { get; set; }
        public int CohortID { get; set; }
        public int ProgramID { get; set; }
        public int ModuleID { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Grade { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<int> AssessmentID { get; set; }
    
        public virtual COHORT COHORT { get; set; }
        public virtual MODULE MODULE { get; set; }
        public virtual PROGRAM PROGRAM { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        public virtual ASSESSMENT ASSESSMENT { get; set; }
    }
}
