USE [master]
GO

/****** Object:  Database [studentDB]    Script Date: 01/12/2022 13:42:32 ******/
CREATE DATABASE [studentDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'studentDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\studentDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'studentDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\studentDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [studentDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [studentDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [studentDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [studentDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [studentDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [studentDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [studentDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [studentDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [studentDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [studentDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [studentDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [studentDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [studentDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [studentDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [studentDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [studentDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [studentDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [studentDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [studentDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [studentDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [studentDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [studentDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [studentDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [studentDB] SET RECOVERY FULL 
GO

ALTER DATABASE [studentDB] SET  MULTI_USER 
GO

ALTER DATABASE [studentDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [studentDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [studentDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [studentDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [studentDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [studentDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [studentDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [studentDB] SET  READ_WRITE 
GO

